config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root                 'pages#home'
  get 'help'     =>    'pages#help'
  get 'about'    =>    'pages#about'
  get 'contact'  =>    'pages#contact'
  get 'signup'   =>    'users#new'

  get 'login'    =>    'sessions#new'
  post 'login'   =>    'sessions#create'
  delete 'logout'=>    'sessions#destroy'

  resources :users
  resources :posts do
    resources :comments, only:[:new, :create, :destroy]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :comment, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  has_attached_file :picture, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"}
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  validates :user_id, presence: true

  # validates :picture, presence: true

  validates :caption, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  before_save { self.email = email.downcase }
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  #password
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please Log in."
        redirect_to login_url
      end
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to users_path(params[:user_id]), success: "Comment posted!"
    else
      redirect_to users_path(params[:user_id])
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to user_path(current_user.id)
    flash[:success] = "Comment Deleted!"
  end

  private
    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @post = current_user.posts.build if logged_in?
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to user_path(current_user.id)
      flash[:success] = "Post Created!"
    else
      redirect_to new_post_path
    end
  end

  def show
    # @user = User.find(params[:id])
    # @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to user_path(current_user.id)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user.id)
    flash[:success] = "Post Deleted!"
  end

  private
    def post_params
      params.require(:post).permit(:picture, :caption)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination, Please try again.'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
    flash[:success] = "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Successfully signed up! Welcome to Wanderlusting!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Successfully Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.all
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Your Profile has been Deleted"
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_cofirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  #logs in the user
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authenticate
    unless logged_in?
      flash[:alert] = "You must be logged in!"
      redirect_to login_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/comments/new.html.erb
<% provide(:title, "Comments") %>

  <div class="new_comment">
  <h3>Post a comment!</h3>
    <section class="post_form">
      <%= form_for @comment, url: post_comments_path(params[:post_id]) do |f| %>

      <div class="field">

      <%= f.label :comment %>
      <%= f.text_area :comment, placeholder: "Leave a comment!" %>
      </div>

      <%= f.submit "Post", class: "btn btn-primary" %>
      <% end %>
    </section>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Wanderlusting</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Wanderlusting", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Discover", users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
              <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log In", login_path %></li>
          <% end %>
        </nav>
      </div>
    </header>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>

    </div>
        <footer class="footer">
      <small>
        &copy;2016 <a href="#">Wanderlusting</a> by <a href="http://www.instagram.com/knowledge">@Knowledge</a>
      </small>
      <nav>
        <ul>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </nav>
    </footer>
    <!-- debug box
  <%= debug(params) %> -->
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>

<div class="center jumbotron">
    <h1>About Wanderlusting</h1>
    <p>Wanderlusting is a community of travelers just like you! With a Wanderlusting account
     you will be able to create your own travel posts and follow other wanderlusters for travel inspiration and tips!
    <br>
    <br>
    <%= link_to "Sign Up Now!", signup_path, class: "btn btn-lg btn-primary" %>
    </p>
</div>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>

<div class="center jumbotron">
  <h1>Contact</h1>
  <p class="">
    <a href="mailto:Tupaclypse@gmail.com?Subject=Wanderlusting target="_blank">Email: Knowledge</a>
    <br>
    <a href="http://www.instagram.com/knowledge">Follow @Knowledge on Instagram!</a>
    <br>
    <a href="http://www.twitter.com/knowledgemc">Follow @Knowledge on Twitter!</a>
  </p>
</div>

app/views/pages/help.html.erb
<% provide(:title, "Help") %>
<div class="center jumbotron">
<h1>Welcome to the Help Section!</h1>
<p>Wanderlusting is a fullstack Ruby on Rails application where users
can post Travel pics, as well as view and comment on other users' posts.  It is essentially a travel-focused Instagram clone. </p>
<p>After signing up for an account,
      you will be able to create your own
        travel posts and follow other users!
</p>
<%= link_to "Sign Up Now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<div class="landing">
<div class="center jumbotron">
  <h1>Welcome to Wanderlusting!</h1>

  <p>Home for wanderlusters just like you! Join now for travel pics, tips, and inspiration!
  <br><%= link_to "Learn more...", about_path %></p>

  <%= link_to "Sign Up Now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
</div>

app/views/posts/new.html.erb
  <div class="new_post">
  <h3>Create a new Post!</h3>
    <section class="post_form">
      <%= form_for @post, html: { multipart: true } do |f| %>

      <div class="field">
      <%= f.label :picture %><br>
      <%= f.file_field :picture %>

      <%= f.label :caption %>
      <%= f.text_area :caption, placeholder: "Create a New Post!" %>
      </div>

      <%= f.submit "Post", class: "btn btn-primary" %>
      <% end %>
    </section>
  </div>

app/views/posts/show.html.erb
<div class="row">
  <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="post_form">
        <%= render 'shared/post_form' %>
      </section>
  </aside>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Settings") %>

<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>

    <% end %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>Change Profile Picture on Gravatar</a>
      <br>
      <%= link_to "Delete Profile", @user, method: :delete, data: { confirm: "This is irreversible. Are You Sure?" } %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Discover") %>
<h1>Discover Users</h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>

<h1>Sign Up Here!</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
       <span class="create"> <%= link_to "Create new Post!", new_post_path %></span>
    </section>
  </aside>

  <div class="col-md-8">
    <% if @user.posts.any? %>
      <h3>Posts (<%= @user.posts.count %>)</h3>
      <ol class="posts">
        <% @user.posts.each do |post| %>
          <li id="post-<%= post.id %>">
          <%= link_to gravatar_for(post.user, size: 50), post.user %>
          <span class="user"><%= link_to post.user.name, post.user %></span>
          <br>
          <!-- <span class="picture" style="color:red;"><%= post.picture %></span> -->
          <br>
          <span class="picture"><%= image_tag post.picture.url(:large) %></span>
          <br>
          <span class="content"><%= post.caption %></span>
          <span class="timestamp">
                   Posted <%= time_ago_in_words(post.created_at) %> ago.
            <span class="edit_post">
                  <%= link_to "Edit", edit_post_path(@user, @post) %>
            </span>
              |
            <span class="delete_post">
                  <%= link_to "Delete", post,
                  method: :delete, data:
                    { confirm: "Are you sure you want to delete this post?"} %>
            </span>
              |
            <span class="comment_post">
                  <%= link_to "Comment", new_post_comment_path(post_id: post.id) %>
            </span>

            <div class="comments">
            Comments:<br>
              <% post.comments.each do |comment| %>
                <div><%= comment.comment %> by <%= User.find_by(id: comment.user_id).name %>
                <br>
              <% end %>

            </div>
          </span>
          </li>
        <% end %>
      </ol>
    <% end %>
  </div>
</div>